### ISSUE TITLE
how to convert jpdl4 to bpmn2?

### ISSUE THREAD

**Issue by buptkobe** [droolsjbpm/jbpmmigration#65]
i can't find the file which named 'jpdl4-bpmn2.xsl'

**Comment by eschabell** [comment]
That's correct, this has been only done for 3 to bpmn2. If you like the XSD is available here:

https://github.com/droolsjbpm/jbpmmigration/blob/master/src/main/resources/schema/jpdl/jpdl-4.2.xsd

Use that and the current example to create supporting conversion for the newer 4.2.
